console.log(Boolean(""));        // false
console.log(Boolean("Texto"));   // true
console.log(Boolean(0));         // false
console.log(Boolean(-1));        // true
console.log(Boolean(true));      // true
console.log(Boolean(false));     // false
console.log(Boolean("string"));  // true
console.log(Boolean(null));      // false
console.log(Boolean(undefined)); // false
console.log(Boolean([]));        // true
